version: "3.8"

services:
  flask-app:
    image: gegulusgray/flask-webapp:latest
    ports:
    - "${PORT}"
    restart: unless-stopped
    environment:
      PORT: ${PORT}

  reverse-proxy:
    image:  nginx:1.25-alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    ports:
      - "${PUBLIC_PORT_NGINX}:${PORT_NGINX}"
    environment:
      PORT_NGINX: ${PORT_NGINX}