version: "3.8"

services:
  flask-app:
    container_name: production-api
    image: gegulusgray/flask-webapp:latest
    ports:
    - "${PORT_PUBLIC}:${PORT}"
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      PORT_PUBLIC: 
        ${PUBLIC_PORT_0}
        ${PUBLIC_PORT_1}
        ${PUBLIC_PORT_2}

  reverse-proxy:
    image:  nginx:1.25-alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/reverse_proxy.conf
    depends_on:
      - flask-app
    ports:
      - "${PUBLIC_PORT_NGINX}:${PORT_NGINX}"
    environment:
      PORT_NGINX: ${PORT_NGINX}